/**
 * Regenerate the typed API client from the backend's OpenAPI schema.
 *
 *   npm run generate:api
 *
 * This is a Node script rather than a one-line npm script because the shell that
 * runs npm scripts differs by platform: `${NEXT_PUBLIC_API_BASE:-...}` is POSIX
 * parameter expansion and cmd.exe passes it through verbatim, so the Windows
 * command tried to fetch a URL containing the literal `${...}`. Reading the
 * environment in Node behaves the same everywhere.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import openapiTS, { astToString } from "openapi-typescript";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUTPUT = resolve(HERE, "..", "lib", "api", "generated", "schema.d.ts");

const base = process.env.NEXT_PUBLIC_API_BASE ?? "http://127.0.0.1:8010";
const schemaUrl = new URL("/openapi.json", base);

console.log(`Reading ${schemaUrl}`);

let ast;
try {
  ast = await openapiTS(schemaUrl);
} catch (error) {
  console.error(
    `\nCould not read the OpenAPI schema from ${schemaUrl}.\n` +
      `Start the backend first, or set NEXT_PUBLIC_API_BASE to where it is running.\n`,
  );
  console.error(error.message ?? error);
  process.exit(1);
}

// The openapi-typescript CLI prepends this banner; the programmatic API does not.
// Reproduced verbatim so the output stays byte-identical to what the CLI produced --
// and because "do not hand-edit" is a rule worth stating in the file itself.
const BANNER =
  "/**\n" +
  " * This file was auto-generated by openapi-typescript.\n" +
  " * Do not make direct changes to the file.\n" +
  " */\n\n";

await mkdir(dirname(OUTPUT), { recursive: true });
await writeFile(OUTPUT, BANNER + astToString(ast), "utf8");

console.log(`Wrote ${OUTPUT}`);
