"""initial schema

Revision ID: 4d6069d5fa6d
Revises:
Create Date: 2026-08-07 13:20:23.198098+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "4d6069d5fa6d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assurance_function",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("fte_per_quarter", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "plan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("year"),
    )
    op.create_table(
        "reference_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind", "code", name="uq_reference_kind_code"),
    )
    op.create_index(op.f("ix_reference_data_kind"), "reference_data", ["kind"], unique=False)
    op.create_table(
        "plan_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("author", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("staged_count", sa.Integer(), nullable=False),
        sa.Column(
            "snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plan_version_plan_id"), "plan_version", ["plan_id"], unique=False)
    op.create_table(
        "priority_weight",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("a_risk", sa.Float(), nullable=False),
        sa.Column("b_urgency", sa.Float(), nullable=False),
        sa.Column("c_coverage_gap", sa.Float(), nullable=False),
        sa.Column("d_change", sa.Float(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("set_by", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_priority_weight_plan_id"), "priority_weight", ["plan_id"], unique=False
    )
    op.create_table(
        "sub_team",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assurance_function_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assurance_function_id"], ["assurance_function.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assurance_function_id", "name", name="uq_sub_team_name"),
    )
    op.create_index(
        op.f("ix_sub_team_assurance_function_id"),
        "sub_team",
        ["assurance_function_id"],
        unique=False,
    )
    op.create_table(
        "review",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("ref", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("origin", sa.String(length=40), nullable=False),
        sa.Column("mandated", sa.Boolean(), nullable=False),
        sa.Column("taxonomy_code", sa.String(length=120), nullable=True),
        sa.Column("assurance_function_id", sa.Integer(), nullable=False),
        sa.Column("sub_team_id", sa.Integer(), nullable=True),
        sa.Column("business", sa.String(length=255), nullable=True),
        sa.Column("effort_size", sa.String(length=1), nullable=False),
        sa.Column("fte_override", sa.Integer(), nullable=True),
        sa.Column("regulator", sa.String(length=120), nullable=True),
        sa.Column("regulation", sa.String(length=500), nullable=True),
        sa.Column("rris_ids", sa.String(length=500), nullable=True),
        sa.Column("rca_linked", sa.Boolean(), nullable=False),
        sa.Column("go_live", sa.Date(), nullable=True),
        sa.Column("is_custom", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assurance_function_id"],
            ["assurance_function.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plan.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sub_team_id"],
            ["sub_team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id", "ref", name="uq_review_ref"),
    )
    op.create_index(
        op.f("ix_review_assurance_function_id"), "review", ["assurance_function_id"], unique=False
    )
    op.create_index(op.f("ix_review_plan_id"), "review", ["plan_id"], unique=False)
    op.create_table(
        "approval",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("review_id", sa.Integer(), nullable=False),
        sa.Column("route", sa.String(length=20), nullable=False),
        sa.Column("gate", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("approver", sa.String(length=120), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["review_id"], ["review.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("review_id", "gate", name="uq_approval_gate"),
    )
    op.create_index(op.f("ix_approval_review_id"), "approval", ["review_id"], unique=False)
    op.create_table(
        "audit_entry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("review_id", sa.Integer(), nullable=True),
        sa.Column("review_ref", sa.String(length=40), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("username", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["review_id"], ["review.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_entry_created_at"), "audit_entry", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_entry_review_id"), "audit_entry", ["review_id"], unique=False)
    op.create_table(
        "helios_prestaging",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("review_id", sa.Integer(), nullable=False),
        sa.Column(
            "values",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("target_start", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["review_id"], ["review.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_helios_prestaging_review_id"), "helios_prestaging", ["review_id"], unique=True
    )
    op.create_table(
        "plan_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("review_id", sa.Integer(), nullable=False),
        sa.Column("staged", sa.Boolean(), nullable=False),
        sa.Column("planned_quarter", sa.String(length=2), nullable=True),
        sa.Column("priority_override", sa.Float(), nullable=True),
        sa.Column("priority_override_rationale", sa.Text(), nullable=True),
        sa.Column("descope_rationale", sa.Text(), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["review_id"], ["review.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plan_item_review_id"), "plan_item", ["review_id"], unique=True)
    op.create_table(
        "review_location",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("review_id", sa.Integer(), nullable=False),
        sa.Column("location", sa.String(length=120), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["review_id"], ["review.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("review_id", "location", name="uq_review_location"),
    )
    op.create_index(
        op.f("ix_review_location_review_id"), "review_location", ["review_id"], unique=False
    )
    op.create_table(
        "review_note",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("review_id", sa.Integer(), nullable=False),
        sa.Column("author", sa.String(length=120), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["review_id"], ["review.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_review_note_review_id"), "review_note", ["review_id"], unique=False)
    op.create_table(
        "review_score",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("review_id", sa.Integer(), nullable=False),
        sa.Column("risk", sa.Float(), nullable=False),
        sa.Column("urgency", sa.Float(), nullable=False),
        sa.Column("coverage_gap", sa.Float(), nullable=False),
        sa.Column("change", sa.Float(), nullable=False),
        sa.Column("as_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=120), nullable=False),
        sa.ForeignKeyConstraint(["review_id"], ["review.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_review_score_review_id"), "review_score", ["review_id"], unique=False)
    op.create_table(
        "steward_consultation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("review_id", sa.Integer(), nullable=False),
        sa.Column("steward_name", sa.String(length=255), nullable=False),
        sa.Column("recorded_by", sa.String(length=120), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["review_id"], ["review.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_steward_consultation_review_id"),
        "steward_consultation",
        ["review_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_steward_consultation_review_id"), table_name="steward_consultation")
    op.drop_table("steward_consultation")
    op.drop_index(op.f("ix_review_score_review_id"), table_name="review_score")
    op.drop_table("review_score")
    op.drop_index(op.f("ix_review_note_review_id"), table_name="review_note")
    op.drop_table("review_note")
    op.drop_index(op.f("ix_review_location_review_id"), table_name="review_location")
    op.drop_table("review_location")
    op.drop_index(op.f("ix_plan_item_review_id"), table_name="plan_item")
    op.drop_table("plan_item")
    op.drop_index(op.f("ix_helios_prestaging_review_id"), table_name="helios_prestaging")
    op.drop_table("helios_prestaging")
    op.drop_index(op.f("ix_audit_entry_review_id"), table_name="audit_entry")
    op.drop_index(op.f("ix_audit_entry_created_at"), table_name="audit_entry")
    op.drop_table("audit_entry")
    op.drop_index(op.f("ix_approval_review_id"), table_name="approval")
    op.drop_table("approval")
    op.drop_index(op.f("ix_review_plan_id"), table_name="review")
    op.drop_index(op.f("ix_review_assurance_function_id"), table_name="review")
    op.drop_table("review")
    op.drop_index(op.f("ix_sub_team_assurance_function_id"), table_name="sub_team")
    op.drop_table("sub_team")
    op.drop_index(op.f("ix_priority_weight_plan_id"), table_name="priority_weight")
    op.drop_table("priority_weight")
    op.drop_index(op.f("ix_plan_version_plan_id"), table_name="plan_version")
    op.drop_table("plan_version")
    op.drop_index(op.f("ix_reference_data_kind"), table_name="reference_data")
    op.drop_table("reference_data")
    op.drop_table("plan")
    op.drop_table("assurance_function")
    # ### end Alembic commands ###
